Repository NewForce-Cohort-6/tabloidmvc-the-caramel-apple-pops, pull requests merged in 2022-11, with the labels that each got.

#3 Jg view all tags 13
  TabloidMVC/Controllers/TagController.cs
  TabloidMVC/Models/Tag.cs
  TabloidMVC/Repositories/ITagRepository.cs
  TabloidMVC/Repositories/TagRepository.cs
  TabloidMVC/Startup.cs
  TabloidMVC/Views/Shared/_Layout.cshtml
  TabloidMVC/Views/Tag/Index.cshtml
  TabloidMVC/appsettings.json
Labels: Good to go

#5 Jg create tag 14
  TabloidMVC/Controllers/TagController.cs
  TabloidMVC/Repositories/ITagRepository.cs
  TabloidMVC/Repositories/TagRepository.cs
  TabloidMVC/Views/Tag/Create.cshtml
Labels: Good to go

#8 Ja deleteacategory ticket11
  .vscode/launch.json
  .vscode/tasks.json
  TabloidMVC/Controllers/CategoryController.cs
  TabloidMVC/Repositories/CategoryRepository.cs
  TabloidMVC/Repositories/ICategoryRepository.cs
  TabloidMVC/Views/Category/Delete.cshtml
  TabloidMVC/Views/Category/Index.cshtml
  TabloidMVC/Views/Category/NoDelete.cshtml
Labels: Needs Review--Peer

#11 Jg delete error message
  TabloidMVC/Controllers/TagController.cs
  TabloidMVC/Views/Tag/NoDelete.cshtml
Labels: Good to go

#12 Ticket 8-- Edit a Post
  TabloidMVC/Controllers/PostController.cs
  TabloidMVC/Repositories/IPostRepository.cs
  TabloidMVC/Repositories/PostRepository.cs
  TabloidMVC/Views/Post/Edit.cshtml
Labels: Needs Review--Peer

#13 Jg edit tag 16
  TabloidMVC/Controllers/TagController.cs
  TabloidMVC/Repositories/ITagRepository.cs
  TabloidMVC/Repositories/TagRepository.cs
  TabloidMVC/Views/Tag/Edit.cshtml
  TabloidMVC/Views/Tag/NoEdit.cshtml
Labels: Needs Review--Peer

#14 Bug Fix conditional render edit and delete buttons
  TabloidMVC/Controllers/PostController.cs
  TabloidMVC/Models/ViewModels/PostUserViewModel.cs
  TabloidMVC/Views/Post/Index.cshtml
Labels: enhancement, Needs Review--Peer
